# -*- coding: utf-8 -*-
"""task3_Password_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPYJr8JzUneXOo5XkFDeHLdecB_PRTH6
"""

import random
import string

max_len = 12
min_len = 6
while True:
    try:
        user_input = int(input("Enter the length of the Password: "))
    except TypeError:
        print("Please enter the correct value not in string.")
    if user_input < min_len or user_input > max_len :
        print("Please enter the length of the password between 8 and 12.")
    else:
        break

print("""\nChoose password complexity:
      1. Letters Only
      2. Letters + Numbers
      3. Letters + Numbers + Special Characters""")
while True:
    user_choice = input("Enter the choice: ")
    try:
      if user_choice == "1":
        character = string.ascii_letters
        break
      elif user_choice == "2":
        character = (string.ascii_letters + string.digits)
        break
      elif user_choice == "3":
        character = (string.ascii_letters + string.digits + string.punctuation)
        break
      else:
        print("Please make a valid choice.")
    except TypeError:
       print("Enter the number please.")

def generated_pass(length, characters):
   password = ""
   for _ in range(length):
      password += random.choice(characters)
   return password

def strength_checker(password):
    length = len(password)
    letters = any(char.isalpha() for char in password)
    digits = any(char.isdigit() for char in password)
    special = any(char in string.punctuation for char in password)

    if length >= 8 and letters and digits and special:
       return "strong"
    elif length >= 6 and letters and digits :
       return "medium"
    else:
       return "weak"


while True:
   password = generated_pass(user_input, character)
   strength = strength_checker(password)
   print(f"Generated Password: {password}")
   print(f"Strength: {strength}")

   try_again = input("you are interested to regenerate the password ?").lower()
   if try_again != "yes" :
      print("Password generated completed, goodbye!.")
      break