# -*- coding: utf-8 -*-
"""task2_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPYJr8JzUneXOo5XkFDeHLdecB_PRTH6
"""

def add(x, y):
    return x+y

def sub(x, y):
    return x - y

def mul(x, y):
    return x * y

def div(x, y):
    return x / y

def modul(x, y):
    return x % y

while True:
    operation_choice = input("Enter Your choice(+,-,/,*,%): ")

    if operation_choice == "exit" or operation_choice == "Exit" :
        break

    xnum = float(input("Enter the first value: "))
    ynum = float(input("Enter the second value: "))
    if operation_choice == "+":
        print(f"The Result is: {add(xnum, ynum)}")
    elif operation_choice == "-":
        print(f"The Result is: {sub(xnum, ynum)}")
    elif operation_choice == "*":
        print(f"The Result is: {mul(xnum, ynum)}")
    elif operation_choice == "/":
        print(f"The Result is: {div(xnum, ynum)}")
    elif operation_choice == "%":
        print(f"The Result is: {modul(xnum, ynum)}")
    else:
        print("Invalid operator choice! please make a valid preference.")