# -*- coding: utf-8 -*-
"""task1_To-D0_List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPYJr8JzUneXOo5XkFDeHLdecB_PRTH6
"""

class To_do_list:
    def __init__(self):
        self.tasks = [] # Initialize tasks as an instance variable
        self.menu()

    def menu(self):
        print("""
                1. Add a new task
                2. View all tasks
                3. Update a task
                4. Mark task as completed
                5. Exit """)

        while True :
          user_input = input("Enter Your Choice(1-5): ")

          if user_input == "1" :
            self.add_task()
          elif user_input == "2" :
            self.view_task()
          elif user_input == "3" :
            self.update_task()
          elif user_input == "4" :
            self.task_update()
          elif user_input == "5" :
            self.exit()
            break
          else:
            print("Invalid preference ! Please enter the correct One to perform any operation.")

    def add_task(self):
        user = input("Enter the task: ")
        self.tasks.append(user) # Use append to add the whole string, and self.tasks
        print("\nTask added Successfully.")

    def view_task(self):
        if not self.tasks : # Check self.tasks for emptiness
           print("Your Task list is Empty.")
        else:
           print("\n----- Your Task List ------")
           for i, task_item in enumerate(self.tasks): # Iterate over self.tasks
                print(f"{i + 1}. {task_item}")


    def update_task(self):
        if not self.tasks:
            print("Your to-do list is empty. Nothing to update.")
            return

        self.view_task() # Show tasks to help user choose
        try:
            task_index = int(input("Enter the number of the task to update: ")) - 1
            if 0 <= task_index < len(self.tasks):
                new_task_description = input(f"Enter the new description for task '{self.tasks[task_index]}': ")
                self.tasks[task_index] = new_task_description
                print(f"\nTask updated to: '{new_task_description}'")
            else:
                print("Invalid task number.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    def task_update(self): # This method marks a task as completed (removes it)
        if not self.tasks:
            print("Your to-do list is empty. Nothing to complete.")
            return

        self.view_task() # Show tasks to help user choose
        try:
            task_to_complete_index = int(input("Enter the number of the task to mark as complete: ")) - 1
            if 0 <= task_to_complete_index < len(self.tasks):
                completed_task = self.tasks.pop(task_to_complete_index) # Remove by index
                print(f"Task '{completed_task}' marked as complete and removed.")
            else:
                print("Invalid task number.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    def exit(self):
       print("Exit From To-Do list.\nHave a nice day.")

to = To_do_list()
# The print(to) statement will print the object's memory address, which is generally not intended here.
# If you want to confirm the object is created, you can keep it, but it doesn't show tasks.
# print(to)