# -*- coding: utf-8 -*-
"""task5_Contact_Book.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPYJr8JzUneXOo5XkFDeHLdecB_PRTH6
"""

import json
import os

class ContactManager:
    def __init__(self, filename="contacts.json"):
        self.filename = filename
        self.contacts = self.load_contacts()
        self.show_menu()

    def show_menu(self):
        print("\n-------This is Menu-------")
        print("1. Add Contact")
        print("2. View Contacts")
        print("3. Search Contact")
        print("4. Update Contact")
        print("5. Delete Contact")
        print("6. Exit")

        while True:
            user_choice = input("\nEnter your choice (1-6): ")
            try:
                choice = int(user_choice)
                if choice == 1:
                    self.add_contact()
                elif choice == 2:
                    self.view_contacts()
                elif choice == 3:
                    self.search_contact()
                elif choice == 4:
                    self.update_contact()
                elif choice == 5:
                    self.delete_contact()
                elif choice == 6:
                    self.save_contacts()
                    print("Exiting Contact Book. Goodbye!")
                    break
                else:
                    print("Please enter a valid choice between 1 and 6.")
            except ValueError:
                print("Invalid input. Please enter a number.")

    def save_contacts(self):
        with open(self.filename, "w") as file:
            json.dump(self.contacts, file, indent=4)
        print("Contacts saved successfully!")

    def load_contacts(self):
        if os.path.exists(self.filename):
            with open(self.filename, "r") as file:
                return json.load(file)
        return {} # Return an empty dictionary if file does not exist

    def validate_email(self, email):
        if email and '@' in email and '.' in email:
            return True
        return False

    def is_duplicate(self, name):
        return name in self.contacts

    def add_contact(self):
        print("\n--- Add New Contact ---")
        while True:
            user_name = input("Enter Name: ").title()
            if not user_name:
                print("Name cannot be empty. Please try again.")
                continue
            if self.is_duplicate(user_name):
                print(f"Contact with name '{user_name}' already exists. Please choose a different name or update the existing contact.")
            else:
                break

        while True:
            try:
                user_phno = int(input("Enter Phone Number: "))
                break
            except ValueError:
                print("Invalid phone number. Please enter digits only.")

        while True:
            user_email = input("Enter Email (optional): ").lower()
            if user_email and not self.validate_email(user_email):
                print("Invalid email format. Email must include '@' and '.'. Please try again or leave blank.")
            else:
                break

        user_address = input("Enter Address (optional): ").title()

        self.contacts[user_name] = {
            "phone_no": user_phno,
            "email": user_email,
            "address": user_address
        }
        print(f"Contact '{user_name}' added successfully!")
        self.save_contacts()

    def view_contacts(self):
        print("\n--- Your Contacts ---")
        if not self.contacts:
            print("Your contact list is Empty.")
        else:
            for name, details in self.contacts.items():
                print(f"\nName: {name}")
                print(f"  Phone: {details['phone_no']}")
                print(f"  Email: {details['email'] if details['email'] else 'N/A'}")
                print(f"  Address: {details['address'] if details['address'] else 'N/A'}")

    def search_contact(self):
        print("\n--- Search Contact ---")
        search_term = input("Enter name to search: ").title()
        if search_term in self.contacts:
            details = self.contacts[search_term]
            print(f"\nContact Found for '{search_term}':")
            print(f"  Phone: {details['phone_no']}")
            print(f"  Email: {details['email'] if details['email'] else 'N/A'}")
            print(f"  Address: {details['address'] if details['address'] else 'N/A'}")
        else:
            print(f"Contact '{search_term}' not found.")

    def update_contact(self):
        print("\n--- Update Contact ---")
        self.view_contacts() # Show contacts to help user choose
        if not self.contacts:
            return # Exit if no contacts to update

        contact_to_update = input("Enter the name of the contact to update: ").title()
        if contact_to_update in self.contacts:
            print(f"Updating contact: {contact_to_update}")
            details = self.contacts[contact_to_update]

            # Allow updating each field
            while True:
                try:
                    new_phno_str = input(f"Enter new Phone Number (current: {details['phone_no']}) or press Enter to keep: ")
                    if new_phno_str:
                        details['phone_no'] = int(new_phno_str)
                    break
                except ValueError:
                    print("Invalid phone number. Please enter digits only.")

            while True:
                new_email = input(f"Enter new Email (current: {details['email'] if details['email'] else 'N/A'}) or press Enter to keep: ").lower()
                if new_email and not self.validate_email(new_email):
                    print("Invalid email format. Email must include '@' and '.'. Please try again or leave blank.")
                else:
                    details['email'] = new_email if new_email else details['email']
                    break

            new_address = input(f"Enter new Address (current: {details['address'] if details['address'] else 'N/A'}) or press Enter to keep: ").title()
            if new_address:
                details['address'] = new_address

            self.contacts[contact_to_update] = details
            print(f"Contact '{contact_to_update}' updated successfully!")
            self.save_contacts()
        else:
            print(f"Contact '{contact_to_update}' not found.")

    def delete_contact(self):
        print("\n--- Delete Contact ---")
        self.view_contacts() # Show contacts to help user choose
        if not self.contacts:
            return # Exit if no contacts to delete

        contact_to_delete = input("Enter the name of the contact to delete: ").title()
        if contact_to_delete in self.contacts:
            del self.contacts[contact_to_delete]
            print(f"Contact '{contact_to_delete}' deleted successfully!")
            self.save_contacts()
        else:
            print(f"Contact '{contact_to_delete}' not found.")

contact_book = ContactManager()